package team.rainfall.fontFix.utils;

import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.utils.GdxRuntimeException;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

/**
 * Generated by GLM-4.6
 * 一个用于解析 MP3 文件时长的工具类。
 * <p>
 * 该实现通过分析 MPEG 帧头来计算时长，对于 CBR 和 VBR 文件均有效。
 * 它采用采样估算的方法以避免遍历整个文件，从而提高性能。
 */
public class MP3DurationParser {

    // MPEG 版本
    private static final int MPEG_VERSION_1 = 3;
    private static final int MPEG_VERSION_2 = 2;
    private static final int MPEG_VERSION_2_5 = 0;

    // MPEG 层
    private static final int LAYER_III = 1;

    // 采样率索引表 [version][index]
    private static final int[][] SAMPLE_RATES = {
            {11025, 12000, 8000},   // MPEG Version 2.5
            {-1, -1, -1},           // Reserved
            {22050, 24000, 16000},  // MPEG Version 2
            {44100, 48000, 32000}   // MPEG Version 1
    };

    // 每帧采样数表 [version][layer]
    private static final int[][] SAMPLES_PER_FRAME = {
            {-1, 576, 1152}, // MPEG Version 2.5
            {-1, -1, -1},    // Reserved
            {-1, 576, 1152}, // MPEG Version 2
            {-1, 1152, 1152} // MPEG Version 1
    };

    /**
     * 获取 MP3 文件的时长（秒）。
     *
     * @param file 要解析的 MP3 文件句柄。
     * @return 文件的时长，单位为秒。
     * @throws GdxRuntimeException 如果文件不是有效的 MP3 或读取时发生错误。
     */
    public static float getMP3Duration(FileHandle file) {
        try {
            FrameInfo firstFrame = findFirstFrame(file);
            if (firstFrame == null) {
                throw new GdxRuntimeException("No valid MP3 frame found in file: " + file.path());
            }

            FrameInfo lastFrame = findLastFrame(file);
            if (lastFrame == null) {
                // 如果找不到最后一帧（例如文件非常小），则只根据第一帧估算
                // 这种情况非常罕见，通常意味着文件损坏或只有一个帧
                return (float) firstFrame.frameSize / firstFrame.bitRate * 8;
            }

            // 估算总时长
            // 总数据长度 = 最后一帧的位置 + 最后一帧的大小 - 第一帧的位置
            long dataLength = lastFrame.position + lastFrame.frameSize - firstFrame.position;
            // 平均帧大小 (字节)
            float averageFrameSize = (float) dataLength / (lastFrame.position - firstFrame.position + 1) * firstFrame.frameSize;
            // 估算总帧数
            long estimatedFrameCount = (long) (dataLength / averageFrameSize);
            // 总时长 = 估算总帧数 * 每帧时长
            return estimatedFrameCount * firstFrame.durationPerFrame;

        } catch (IOException e) {
            throw new GdxRuntimeException("Error reading MP3 file: " + file.path(), e);
        }
    }

    /**
     * 查找并解析文件中的第一个有效 MPEG 帧。
     */
    private static FrameInfo findFirstFrame(FileHandle file) throws IOException {
        try (InputStream in = file.read()) {
            byte[] buffer = new byte[4096];
            int read;
            // 读取文件开头部分
            while ((read = in.read(buffer)) != -1) {
                for (int i = 0; i < read - 3; i++) {
                    // MPEG 帧同步字为 11个 '1'，即 0xFFE
                    if ((buffer[i] & 0xFF) == 0xFF && (buffer[i + 1] & 0xE0) == 0xE0) {
                        FrameInfo frameInfo = parseFrameHeader(buffer, i);
                        if (frameInfo != null) {
                            // 设置全局文件中的绝对位置
                            frameInfo.position = i;
                            return frameInfo;
                        }
                    }
                }
            }
        }
        return null;
    }

    /**
     * 查找并解析文件中的最后一个有效 MPEG 帧。
     */
    private static FrameInfo findLastFrame(FileHandle file) throws IOException {
        final int MAX_SEARCH = 65536; // 与 OGG 解析器保持一致的搜索范围
        long fileSize = file.length();
        if (fileSize < 4) return null;

        int searchSize = (int) Math.min(fileSize, MAX_SEARCH);
        long startOffset = fileSize - searchSize;

        try (InputStream in = file.read()) {
            long skipped = in.skip(startOffset);
            if (skipped != startOffset) return null;

            byte[] tail = new byte[searchSize];
            int totalRead = 0;
            while (totalRead < searchSize) {
                int read = in.read(tail, totalRead, searchSize - totalRead);
                if (read <= 0) break;
                totalRead += read;
            }

            // 从后向前搜索
            for (int i = totalRead - 4; i >= 0; i--) {
                if ((tail[i] & 0xFF) == 0xFF && (tail[i + 1] & 0xE0) == 0xE0) {
                    FrameInfo frameInfo = parseFrameHeader(tail, i);
                    if (frameInfo != null) {
                        // 设置全局文件中的绝对位置
                        frameInfo.position = startOffset + i;
                        return frameInfo;
                    }
                }
            }
        }
        return null;
    }

    /**
     * 解析 MPEG 帧头，提取关键信息。
     *
     * @param data  包含帧头的字节数组。
     * @param offset 帧头在数组中的起始偏移量。
     * @return 包含帧信息的 FrameInfo 对象，如果帧头无效则返回 null。
     */
    private static FrameInfo parseFrameHeader(byte[] data, int offset) {
        if (offset + 3 >= data.length) return null;

        int header = ByteBuffer.wrap(data, offset, 4).order(ByteOrder.BIG_ENDIAN).getInt();

        int versionBits = (header >> 19) & 0x3;
        int layerBits = (header >> 17) & 0x3;
        int bitrateIndex = (header >> 12) & 0xF;
        int samplingRateIndex = (header >> 10) & 0x3;
        int paddingBit = (header >> 9) & 0x1;

        // 验证版本和层
        if (versionBits == 1 || layerBits != LAYER_III) {
            return null; // 不是有效的 MP3 Layer III 帧
        }

        // 验证比特率和采样率索引
        if (bitrateIndex == 0 || bitrateIndex == 15 || samplingRateIndex == 3) {
            return null; // 无效或保留的索引值
        }

        int version = (versionBits == 3) ? MPEG_VERSION_1 : MPEG_VERSION_2;
        int sampleRate = SAMPLE_RATES[versionBits][samplingRateIndex];
        if (sampleRate == -1) return null;

        // 比特率表 (kbps) [version][bitrateIndex]
        int bitRate = getBitRate(version, layerBits, bitrateIndex);

        int samplesPerFrame = SAMPLES_PER_FRAME[versionBits][layerBits];
        float durationPerFrame = (float) samplesPerFrame / sampleRate;

        // 计算帧大小
        // FrameSize = (SamplesPerFrame / 8 * BitRate * 1000) / SampleRate + Padding
        int frameSize = (int) ((samplesPerFrame / 8.0 * bitRate) / sampleRate + paddingBit);

        FrameInfo info = new FrameInfo();
        info.sampleRate = sampleRate;
        info.bitRate = bitRate;
        info.frameSize = frameSize;
        info.durationPerFrame = durationPerFrame;
        return info;
    }

    private static int getBitRate(int version, int layerBits, int bitrateIndex) {
        int[][] bitrates = (version == MPEG_VERSION_1)
                ? new int[][]{{0, 32, 64, 96, 128, 160, 192, 224, 256, 288, 320, 352, 384, 416, 448, -1},
                {0, 32, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, 384, -1},
                {0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320, -1}}
                : new int[][]{{0, 32, 48, 56, 64, 80, 96, 112, 128, 144, 160, 176, 192, 224, 256, -1},
                {0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160, -1},
                {0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160, -1}};

        int bitRate = bitrates[layerBits - 1][bitrateIndex] * 1000; // 转换为 bps
        return bitRate;
    }

    /**
     * 内部类，用于存储从帧头解析出的信息。
     */
    private static class FrameInfo {
        long position;         // 帧在文件中的绝对位置
        int sampleRate;        // 采样率
        int bitRate;           // 比特率
        int frameSize;         // 帧大小（字节）
        float durationPerFrame; // 每帧的时长（秒）
    }
}
